---
- name: Load var file with package names based on the OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install Xfce desktop environment
  package:
    name:
      "{{ package_names }}"

# TODO: Does this need to be generalized?  Should it be broken out
# into a separate role?  See this issue:
# https://github.com/cisagov/ansible-role-xfce/issues/7
- name: Disable screen locking
  file:
    path: /etc/xdg/autostart/light-locker.desktop
    state: absent
