---
- name: Load var file with package names based on the OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install Xfce desktop environment
  package:
    name:
      "{{ package_names }}"

# Does this go here?  Can this be generalized?
- name: Disable screen locking
  file:
    path: /etc/xdg/autostart/light-locker.desktop
    state: absent
